/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto1.Menu;

import com.mycompany.proyecto1.Analisis.RecuperarErrores;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */
public class ReporteError extends javax.swing.JPanel {

    private panelPrincipal panel;
    DefaultTableModel modelo;

    /**
     * Creates new form ReporteError
     */
    public ReporteError(panelPrincipal panel) {
        this.panel = panel;
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Cadena");
        modelo.addColumn("Simbolo");
        modelo.addColumn("Fila,Columna");
        modelo.addColumn("¿Que esperaba?");
        this.tabla.setModel(modelo);
        agregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"asd", "asd", "asd", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cadena", "Simbolo", "Fila,columna", "¿Que esperaba?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    public void agregar() {
        for (com.mycompany.proyecto1.Analisis.Error errore : panel.getIzqueirda().getLectura().getErrores()) {
            String[] info = new String[4];
            info[0] = errore.getError();
            info[1] = String.valueOf(errore.getLexema());
            info[2] = errore.getFila() + "/" + errore.getColumna();
            info[3] = errore.getTipo();
            modelo.addRow(info);
        }
        RecuperarErrores nuevo = new RecuperarErrores(panel.getIzqueirda().getLectura().getErrores(), panel.getIzqueirda().getLectura().getNuevo().getEstados());
        RErrores nuevo1 = new RErrores();
        for (String object : nuevo.getRecuperacion()) {
            nuevo1.getjTextArea1().append(object + "\n");
        }
        nuevo1.setVisible(true);

    }
}
